# Generated by Django 3.2.16 on 2023-01-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230131_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='webadmin',
            name='profile_pic',
            field=models.FileField(upload_to=''),
        ),
    ]
