# Generated by Django 3.2.16 on 2023-02-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230131_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
