# Generated by Django 3.2.16 on 2023-02-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_staffs_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='status',
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
