# Generated by Django 3.2.16 on 2023-02-01 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_staffs_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='profile_pic',
        ),
    ]
