# Generated by Django 3.2.16 on 2023-02-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_staff_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='profile_pic',
            field=models.FileField(blank=True, default='gsggsg', upload_to=''),
        ),
    ]
