# Generated by Django 3.2.16 on 2023-02-02 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_staff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='profile_pic',
        ),
        migrations.DeleteModel(
            name='WebAdmin',
        ),
    ]
