# Generated by Django 3.2.16 on 2023-02-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
