# Generated by Django 3.2.16 on 2023-01-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('about', models.TextField()),
                ('abouttxt', models.TextField(default='')),
                ('general_address', models.TextField(default='')),
                ('fb', models.CharField(default='-', max_length=30)),
                ('tw', models.CharField(default='-', max_length=30)),
                ('insta', models.CharField(default='-', max_length=30)),
                ('yt', models.CharField(default='-', max_length=30)),
                ('tell', models.CharField(default='-', max_length=30)),
                ('link', models.CharField(default='-', max_length=30)),
                ('set_name', models.CharField(default='-', max_length=30)),
                ('picurl', models.TextField(default='')),
                ('picname', models.TextField(default='')),
                ('picurl2', models.TextField(default='')),
                ('picname2', models.TextField(default='')),
            ],
        ),
    ]
