# Generated by Django 3.2.16 on 2023-02-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_homepage_mainslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainslider',
            name='images',
            field=models.ImageField(default='', upload_to='assets/frontend/images/main-sliders'),
        ),
    ]
