# Generated by Django 3.2.16 on 2023-02-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_mainslider_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainslider',
            name='images',
            field=models.ImageField(blank=True, default='gdggd', upload_to='assets/frontend/images/main-sliders'),
        ),
    ]
