# Generated by Django 3.2.16 on 2023-02-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_mainslider_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='services',
            field=models.CharField(default='SErvices List', max_length=200),
        ),
        migrations.AddField(
            model_name='pages',
            name='working_day',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='pages',
            name='working_hours',
            field=models.CharField(default='No Work', max_length=200),
        ),
        migrations.AddField(
            model_name='pages',
            name='working_hours_txt_name',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
