# Generated by Django 3.2.16 on 2023-02-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20230204_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='site_email',
            field=models.EmailField(default='site@email.com', max_length=254),
        ),
    ]
