# Generated by Django 3.2.16 on 2023-02-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_pages_site_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='name',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='pages',
            name='services',
            field=models.CharField(default='Services List', max_length=200),
        ),
    ]
