# Generated by Django 3.2.16 on 2023-02-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_pages_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pages',
            name='picurl',
            field=models.TextField(default='', max_length=200),
        ),
    ]
