# Generated by Django 3.2.16 on 2023-02-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20230205_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='fb',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='pages',
            name='insta',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='pages',
            name='link',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='pages',
            name='set_name',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='pages',
            name='tell',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='pages',
            name='tw',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='pages',
            name='yt',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
