# Generated by Django 3.2.16 on 2023-02-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20230205_0453'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(default='-', max_length=200)),
                ('working_hours_txt_name', models.CharField(default='-', max_length=200)),
                ('working_day', models.CharField(default='-', max_length=200)),
                ('working_hours', models.CharField(default='No Work', max_length=200)),
                ('services', models.CharField(default='Services List', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='pages',
            name='services',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='set_name',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='working_day',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='working_hours',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='working_hours_txt_name',
        ),
    ]
