# Generated by Django 3.2.16 on 2023-02-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20230206_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pages',
            options={'verbose_name': 'page', 'verbose_name_plural': 'pages'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='achi_description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='achi_image',
            field=models.ImageField(blank=True, default='', upload_to='assets/images/achievements/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='achi_title',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='our_mission',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='our_strategy',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='our_trademark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='our_vision',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='strengh',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
